library(Seurat)
library(monocle)
library(AUCell)
library(GSEABase)
library(singscore)
library(garnett)
library(GSVA)

runAucell = function(obj,geneSets){
  set.seed(42)
  #expr = FetchData(obj,vars=rownames(obj@assays$RNA@data) ,slot="data")
  #Retrieve normalized counts matrix
  expr = FetchData(obj,vars=rownames(obj@assays$SCT@data) ,slot="data")
  exprMatrix <- t(expr)
  #Find intersection of gene names between gene sets and Seurat object
  geneSets <- subsetGeneSets(geneSets, rownames(exprMatrix))
  geneSets <- setGeneSetNames(geneSets, newNames=paste(names(geneSets), " (", nGenes(geneSets) ,"g)", sep=""))
  countsPerGene <- apply(exprMatrix, 1, function(x) sum(x>0))
  #Run AUCell rankings and calculations
  cells_rankings <- AUCell_buildRankings(exprMatrix, nCores=4, plotStats=TRUE)
  cells_AUC <- AUCell_calcAUC(geneSets, cells_rankings)
  cells_assignment <- AUCell_exploreThresholds(cells_AUC, plotHist=F, assign=TRUE)
  selectedThresholds <- getThresholdSelected(cells_assignment)
  #AUCell_plotTSNE(tSNE=obj@reductions$umap@cell.embeddings[,1:2],
  #  exprMat=exprMatrix,plots = c("AUC","binaryAUC"),#, "binaryAUC", "AUC","expression"),
  #  cellsAUC=cells_AUC[1:4,])
  return(cells_AUC)
}

#Import gene sets from CCBR database. NB: There are two versions from MSigDB, v6.0 and v7.2, and two sets of species, human and mouse. Mouse was generated by using 
hallmark_mouse = GSEABase::getGmt("/data/CCBR_Pipeliner/db/PipeDB/MSigDB/h.all.v6.0.symbols_mouse.gmt")
c2cp_mouse = GSEABase::getGmt("/data/CCBR_Pipeliner/db/PipeDB/MSigDB/c2.cp.v6.0.symbols_mouse.gmt")

#AUCell
aucell = runAucell(so,hallmark_mouse)
#To retrieve the AUCell scores for a pathway and insert into metadata: Dummy run with GSEA Hypoxia hallmark set
metaVect = aucell@assays@data[[1]][1,]
obj.resized$Hallmark_hypox = metaVect
FeaturePlot(obj.resized,features=c("Hallmark_hypox"))
saveRDS(aucell, "hallmark_aucell.rds")
#Retrieve AUcell outputs with ReadRDS function

#Running single sample GSEA (ssGSEA)
#Set identity metacolumn for Seurat object
Idents(so) = "SCT_snn_res.0.4"
#Calculate average expression for each identity/cluster
so.averageSample = AverageExpression(so)
#Calculate ssGSEA score for each identity without normalization
hallmark_ssGSEA=gsva(expr = as.matrix(as.data.frame(so.averageSample$SCT)),gset.idx.list = hallmark,method='ssgsea',ssgsea.norm=F)
#Generate heatmap of ssGSEA scores, with pathways in the rows and identities in the columns
pheatmap(hallmark_ssgsea,fontsize_row = 5,fontsize_col=8) #No row scaling for raw scoring.
pheatmap(hallmark_ssgsea,fontsize_row = 5,fontsize_col=8,scale = "row") #Rowscale for relative ssGSEA scoring

